#include <stdio.h>

/*	Each new term in the Fibonacci sequence is generated by 
 *	adding the previous two terms. By starting with 1 and 2, 
 *	the first 10 terms will be:
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *	By considering the terms in the Fibonacci sequence whose 
 *	values do not exceed four million, find the sum of the 
 *	even-valued terms.
 *
 */
 
int main(){
	int result = 0, f1 = 1, f2 = 2;
	int limit = 4000000;
	while (f2 < limit){
		result += (f2 % 2 == 0) ? f2 : 0;
		f2 = f1 + f2;
		f1 = f2 - f1;
	}
	printf("Result: %d \n", result);
	return 0;
}